---
- name: playbook with vars
  hosts: localhost
  gather_facts: yes
  become: yes

  vars:
          newhire: abc
          newhire1: xyz

  tasks:
          - name: Create a new group
            group:
                    name: nasbox
                    state: present

          - name: Create a new user
            user:
                    name: "{{ item }}"
                    comment: This is a new user
                    state: present
                    shell: /bin/bash
                    system: yes
                    createhome: yes
                    group: nasbox

            loop:
                    - 123
                    - "{{ newhire }}"
                    - "{{ newhire1 }}"
