---
- name: Playbook to copy a file
  hosts: planetexpress
  gather_facts: yes # this controls if setup.py

  tasks:
          - name: Copy a file from local controller to remote hosts
            copy:
                    src: ~/ans/files/letsgo.tolunch # this is the src file
                    dest: ~/ # this is to move to the file to (on remote hosts)

