---
- name: My playbook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes

  vars:
          newhires:
                  - user: zachf
                    group: zgroup
                    user: dawnz
                    group: dgroup

  tasks:
         - name: Create a new group
           group: 
                name: "{{ item }}"
                state: present
                loop: "{{ newhires.group }}"

         - name: Create a new user
           user:
                   name: LarryNewHire
                   comment: this is within last 90 days
                   state: present 
                   shell: /bin/bash
                   system: no
                   createhome: yes
                   group: sandbox
                 

                   loop:
                           "{{ newhires }}"

                   loop:
                        - LarryNewHire
                        - "{{ newhire }}"
                        - "{{ newhire2 }}"
                        - "{{ newhire3 }}"
...
