---
- name: My first playbook #this is jsut a name for the playbook
  hosts: localhost
  gather_facts: yes

  tasks:
          - name: connect to dell emc server
          - name: My first task - print to the screen 
            debug: 
                        msg: "I want this to print to the screen"  




