---
- name: My playbook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes

  vars:
          newhire: zachf
          newhire2: dawnz
          newhire3: larryl

  tasks:
          - name: Create a new group
            group:
                    name: sandbox
                    state: present

          - name: Create a new user
            user:
                    name: LarryNewHire
                    comment: New Hire for the Team
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: sandbox

          - name: Create a new user from var
            user:
                    name: "{{ [ newhire, newhire2, newhire3 ] }}"
                    comment: New Hire
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: sandbox
