---
- name: Apache server deploy
  hosts: web
  gather_facts: no
  become: yes

  tasks:
          - name: latest version of apache installed
            package:
                    name: apache2
                    state: latest

          - name: make sure a service is running
            service:
                    name: apache2
                    enabled: yes
                    state: started

          - name: render template
            template:
                    src: index.html.j2
                    dest: /var/www/html/index.html

          - name: bounce apache
            service:
                    name: apache2
                    enabled: yes
                    state: restarted

