---

- name: Learning to work with APIs via URI module
  hosts: localhost
  gather_facts: yes

  vars:
          apiurl: "http://api.open-notify.org/astros.json"
  
  tasks:
          - name: Looking up ISS astros
            uri:
                    url: "{{apiurl}}"
                    return_content: yes
            register: astros

          - name: Dump json out to a file
            copy:
                    content: "{{ astros }}"
                    dest: "astros-{{ ansible_date_time.date }}.txt" 

          - name: debug the results
            debug:
                    var: astros.json.people

          - name: set a new variable to make things easy
            set_fact:
                    spacecowboys: "{{ astros.json.people }}"


...
