---

- name: Learning to work via URI module
  hosts: localhost
  gather_facts: yes
  
  vars: 
        apiurl: "http://api.open-notify.org/astros.json"

  tasks:
          - name: Looking up ISS astros
            uri:
                    url: "{{apiurl}}"
                    return_content: no

            register: astros


          - name: dump json out to a file
            copy:
                    content: "{{astros}}"
                    dest: "astros-{{ansible_date_time.date}}.txt"


          - name: debug the results
            debug:
                    var: astros.json.people
                    #msg: "{{astros.json.peopple}}"


          - name: set a new variable to make things easy
            set_fact:
                    spacecowboys: "{{astros.json.people}}"

          - name: just the names on the screen
            debug:
                    msg: "on the space station is {{item.name.split()[0]}}"

            loop: "{{spacecowboys}}"
