---
- name: My playbook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes


  vars:
          newhires: 
              - user: anil
                group: agroup
              - user: david
                group: dgroup
          
          


  tasks:
          - name: Create a new group
            group:
                    name: "{{item.group}}"
                    state: present 
            loop: "{{newhires}}"


          - name: Create a new user
            user:
                    name: "{{item.user}}"
                    comment: "this is new hire"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: "{{item.group}}"

            loop: "{{newhires}}"




...
