---
- name: My Plybook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes

  vars:
          newhire: zachf
          newhire2: dawnz
          newhire3: larry1


  tasks:

          - name: Create a new group
            group:
                  name: sandbox
                  state: present

          
          - name: Create a new user
            user:
                  name: LarryNewHire
                  comment: This is a hire within the last 90 days
                  state: present
                  shell: /bin/bash
                  system: no
                  createhome: yes
                  group: sandbox

          - name: Create a new user from a var
            user:
                    name: "{{ newhire }}"
                    comment: Can we make this new hire
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: sandbox
