---
- name: Playbook to copy a file into remote hosts
  hosts: planetexpress
  gather_facts: yes 
  become: yes

  vars:
          newhires:
                  - user: zachf
                    group: zgroup
                  - user: dawnz
                    group: dgroup
  tasks:
          - name: create a new group
            group:
                    name: "{{ item.group }}"
                    state: present
            loop: "{{ newhires }}"
          - name: create a new user
            user:
                    name: "{{ item.user }}"
                    comment: Can we make this new hire
                    state: present
                    shell: /bin/bash
                    system: no
                    create_home: yes
                    group: "{{ item.group }}"
            loop: "{{ newhires }}"

...
