---
- name: A playbook using apt
  hosts: planetexpress
  gather_facts: yes 

  vars_files:
          - vars/vars-when.yml
  tasks:
          - name: use apt to install Steam Locomotive
            apt:
                    name: sl
                    state: present
            become: yes
            register: result
            when: ansible_distribution == "Ubuntu"

          - name: print out
            debug:
                    var: result
                    verbosity: 1

          - name: print out
            debug:
                    msg: "The user {{ inventory_hostname }} has a cache_update_time of {{ result.cache_update_time }}"
            when: ansible_distribution == "Ubuntu"

          - debug:
                    var: licensetypes.paytypes[0]
...
