---
- name: Playbook to copy a file to remote hosts
  hosts: planetexpress
  gather_facts: yes

  tasks: 
        - name: Copy a file from controller to remote hosts
          copy:
                  src: ~/ans/files/letsgo.tolunch
                  dest: ~/
