---
- name: My playbook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes

  vars:
          newhire: zachf
          newhire2: dawnz
          newhire3: larryl

  tasks:
          - name: Create a new user from a var
            user:
                    name: "{{ item }}"
                    comment: make the newhire user
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: sandbox
            loop:
                   - newhire
                   - newhire2
                   - newhire3
