---
- name: debug playbook to display ansible facts
  hosts: devhosts:!fansworth
  gather_facts: yes

  vars_files:
          - vars/vars-when.yml

  tasks:
          - name: use apt to install Steam Locomotive
            apt:
                    name: sl
                    state: present
            become: yes
            register: result
            when: ansible_distribution == "Ubuntu"

          - name: print out the values of result, only in verbose=1 mode
            debug:
                    var: result
                    verbosity: 1

          - name: print out cache update time
            debug:
                    msg: "The user {{ inventory_hostname }} has a cache_update_time of {{ result.cache_update_time }}"
            when: ansible_distribution == "Ubuntu"

          - name: showing we know how to read YAML vars
            debug:
                    var: licensetypes.paytypes[0]

...
