---
- name: debug playbook to display ansible facts
  hosts: devhosts:!fansworth
  gather_facts: yes

  tasks:
          - name: use apt to install Steam Locomotive
            apt:
                    name: sl
                    state: present
            become: yes
            register: result

          - name: print out the values of result, only in verbose=1 mode
            debug:
                    var: result
                    verbosity: 1

          - name: print out cache update time
            debug:
                    msg: "The user {{ inventory_hostname }} has a cache_update_time of {{ result.cache_update_time }}"

...
