---
- name: My playbook with vars
  hosts: planetexpress
  gather_facts: yes
  become: yes

  vars:
          newhires: 
              - user: zachf
                group: zgroup
              - user: dawnz
                group: dgroup 

  tasks:
          - name: Create a new group
            group:
                    name: "{{ item.group }}"
                    state: present # state is typically always PRESENT or ABSENT
            loop: "{{ newhires }}"

          - name: Create a new user
            user:
                    name: "{{ item.user }}"
                    comment: This is a hire within the last 90 days
                    state: present  # state is typically always PRESENT or ABSENT
                    shell: /bin/bash
                    system: no
                    create_home: yes
                    group: "{{ item.group }}"
            loop: "{{ newhires }}"
